# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('era', models.CharField(max_length=50)),
                ('gp', models.IntegerField()),
                ('pa', models.IntegerField()),
                ('single', models.IntegerField()),
                ('two', models.IntegerField()),
                ('three', models.IntegerField()),
                ('hr', models.IntegerField()),
                ('bb', models.IntegerField()),
                ('ibb', models.IntegerField(default=0)),
                ('runs', models.IntegerField()),
                ('rbi', models.IntegerField()),
                ('steals', models.IntegerField()),
                ('hbp', models.IntegerField(default=0)),
            ],
        ),
    ]
