# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batter',
            name='wrcplus',
            field=models.IntegerField(default=100),
        ),
    ]
