# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0002_batter_wrcplus'),
    ]

    operations = [
        migrations.AddField(
            model_name='batter',
            name='ba',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='batter',
            name='ops',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='batter',
            name='sf',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='batter',
            name='ubr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='batter',
            name='wgdp',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=3),
        ),
    ]
